name: Checks

on:
  push:
    paths:
      - packages/*/package-lock.json
      - .github/workflows/checks.yaml
      - .github/workflows/license-check.yaml

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
  check-licenses-player:
    needs: setup
    uses: ./.github/workflows/license-check.yaml
    with:
      package: player
  check-licenses-utils:
    needs: setup
    uses: ./.github/workflows/license-check.yaml
    with:
      package: utils
