name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/npm.yaml
  cdn:
    runs-on: ubuntu-latest
    needs: npm
    steps:
      - uses: ./.github/workflows/publish.yaml
        with:
          version: ${{ github.ref_name }}
          latest: true
