name: Update documentation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: |
            packages/player/package-lock.json
      - run: |
          cd packages/player
          npm ci
          npm run build
          npm run docs
          git add docs/api
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git commit -m "Update documentation" || exit 0
          git branch update_docs-${{ github.run_id }}
          git push origin update_docs-${{ github.run_id }}
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository}}/pulls \
          -d '{"title":"Update the documentation","body":"","head":"update_docs-${{ github.run_id }}","base":"${{ github.ref }}"}'
